import type { PrefabDefinition } from '@/types/prefabs'

export const PREFAB_CATEGORIES = [
  { id: 'structures', label: 'Structures' },
  { id: 'cooking', label: 'Cooking & Kitchen' },
  { id: 'seating', label: 'Seating & Furniture' },
  { id: 'landscaping', label: 'Landscaping' },
] as const

export const PREFAB_CATALOG: PrefabDefinition[] = [
  // ── Structures ──
  {
    type: 'pergola',
    label: 'Pergola',
    category: 'structures',
    defaultSize: { widthFt: 12, depthFt: 10, heightFt: 9 },
    minSize: { widthFt: 6, depthFt: 6, heightFt: 7 },
    maxSize: { widthFt: 60, depthFt: 20, heightFt: 12 },
    resizable: true,
    rotatable: true,
    color: '#8b7355',
    editableProps: [
      {
        key: 'postShape',
        label: 'Post Shape',
        type: 'select',
        options: [
          { value: 'square', label: 'Square' },
          { value: 'round', label: 'Round' },
        ],
        defaultValue: 'square',
      },
      {
        key: 'postDiameter',
        label: 'Post Size (in)',
        type: 'number',
        min: 3,
        max: 8,
        step: 1,
        defaultValue: 4,
      },
      {
        key: 'postCount',
        label: 'Posts (per side)',
        type: 'number',
        min: 2,
        max: 10,
        step: 1,
        defaultValue: 2,
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#8b7355',
      },
    ],
  },
  {
    type: 'patio_cover',
    label: 'Patio Cover',
    category: 'structures',
    defaultSize: { widthFt: 12, depthFt: 10, heightFt: 9 },
    minSize: { widthFt: 6, depthFt: 6, heightFt: 7 },
    maxSize: { widthFt: 60, depthFt: 20, heightFt: 12 },
    resizable: true,
    rotatable: true,
    color: '#a0927c',
    editableProps: [
      {
        key: 'roofStyle',
        label: 'Roof Style',
        type: 'select',
        options: [
          { value: 'flat', label: 'Flat' },
          { value: 'tilt', label: 'Slight Tilt' },
          { value: 'gabled', label: 'Gabled' },
        ],
        defaultValue: 'flat',
      },
      {
        key: 'roofPitch',
        label: 'Roof Pitch (in/ft)',
        type: 'number',
        min: 0.5,
        max: 4,
        step: 0.25,
        defaultValue: 1,
      },
      {
        key: 'postShape',
        label: 'Post Shape',
        type: 'select',
        options: [
          { value: 'square', label: 'Square' },
          { value: 'round', label: 'Round' },
        ],
        defaultValue: 'square',
      },
      {
        key: 'postDiameter',
        label: 'Post Size (in)',
        type: 'number',
        min: 3,
        max: 8,
        step: 1,
        defaultValue: 4,
      },
      {
        key: 'postCount',
        label: 'Posts (per side)',
        type: 'number',
        min: 2,
        max: 10,
        step: 1,
        defaultValue: 2,
      },
      {
        key: 'overhang',
        label: 'Overhang (in)',
        type: 'number',
        min: 0,
        max: 24,
        step: 3,
        defaultValue: 6,
      },
      {
        key: 'color',
        label: 'Post/Beam Color',
        type: 'color',
        defaultValue: '#a0927c',
      },
      {
        key: 'roofColor',
        label: 'Roof Color',
        type: 'color',
        defaultValue: '#8b7d6b',
      },
    ],
  },
  {
    type: 'wall',
    label: 'Wall',
    category: 'structures',
    defaultSize: { widthFt: 8, depthFt: 8, heightFt: 4 },
    minSize: { widthFt: 2, depthFt: 0.5, heightFt: 2 },
    maxSize: { widthFt: 30, depthFt: 30, heightFt: 20 },
    resizable: true,
    rotatable: true,
    color: '#8b4513',
    editableProps: [
      {
        key: 'shape',
        label: 'Shape',
        type: 'select',
        options: [
          { value: 'straight', label: 'Straight' },
          { value: 'l_shape', label: 'L-Shape' },
          { value: 'u_shape', label: 'U-Shape' },
        ],
        defaultValue: 'straight',
      },
      {
        key: 'lSide',
        label: 'L Corner',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'left',
      },
      {
        key: 'thickness',
        label: 'Thickness (ft)',
        type: 'number',
        min: 0.5,
        max: 3,
        step: 0.5,
        defaultValue: 1,
      },
      {
        key: 'wallType',
        label: 'Material',
        type: 'select',
        options: [
          { value: 'brick', label: 'Brick' },
          { value: 'stone', label: 'Stone' },
          { value: 'wood', label: 'Wood' },
          { value: 'stucco', label: 'Stucco' },
          { value: 'paver', label: 'Paver' },
        ],
        defaultValue: 'brick',
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#8b4513',
      },
      {
        key: 'windowCount',
        label: 'Windows Per Wall',
        type: 'number',
        min: 0,
        max: 3,
        step: 1,
        defaultValue: 0,
      },
      {
        key: 'windowLayout',
        label: 'Window Layout',
        type: 'select',
        options: [
          { value: 'spread', label: 'Spread' },
          { value: 'centered', label: 'Centered' },
        ],
        defaultValue: 'spread',
      },
      {
        key: 'windowWall1',
        label: 'Windows: Wall 1 (Top)',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'windowWall2',
        label: 'Windows: Wall 2 (Left)',
        type: 'boolean',
        defaultValue: false,
      },
      {
        key: 'windowWall3',
        label: 'Windows: Wall 3 (Right)',
        type: 'boolean',
        defaultValue: false,
      },
      // Door
      {
        key: 'hasDoor',
        label: 'Door',
        type: 'boolean',
        defaultValue: false,
      },
      {
        key: 'doorType',
        label: 'Door Type',
        type: 'select',
        options: [
          { value: 'regular', label: 'Regular' },
          { value: 'sliding_glass', label: 'Sliding Glass' },
        ],
        defaultValue: 'regular',
      },
      {
        key: 'doorPosition',
        label: 'Door Position',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'center',
      },
      {
        key: 'doorWall',
        label: 'Door Wall',
        type: 'select',
        options: [
          { value: '1', label: 'Wall 1' },
          { value: '2', label: 'Wall 2' },
          { value: '3', label: 'Wall 3' },
        ],
        defaultValue: '1',
      },
      // TV
      {
        key: 'hasTV',
        label: 'TV',
        type: 'boolean',
        defaultValue: false,
      },
      {
        key: 'tvSize',
        label: 'TV Size',
        type: 'select',
        options: [
          { value: '40', label: '40"' },
          { value: '55', label: '55"' },
          { value: '65', label: '65"' },
          { value: '75', label: '75"' },
        ],
        defaultValue: '55',
      },
    ],
  },
  {
    type: 'post',
    label: 'Post',
    category: 'structures',
    defaultSize: { widthFt: 0.5, depthFt: 0.5, heightFt: 8 },
    minSize: { widthFt: 0.25, depthFt: 0.25, heightFt: 2 },
    maxSize: { widthFt: 2, depthFt: 2, heightFt: 20 },
    resizable: false,
    rotatable: false,
    color: '#8b7355',
    editableProps: [
      {
        key: 'shape',
        label: 'Shape',
        type: 'select',
        options: [
          { value: 'square', label: 'Square' },
          { value: 'round', label: 'Round' },
        ],
        defaultValue: 'square',
      },
      {
        key: 'postSize',
        label: 'Size (in)',
        type: 'number',
        min: 3,
        max: 12,
        step: 1,
        defaultValue: 6,
      },
      {
        key: 'postHeight',
        label: 'Height (ft)',
        type: 'number',
        min: 2,
        max: 20,
        step: 0.5,
        defaultValue: 8,
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#8b7355',
      },
    ],
  },
  {
    type: 'roof',
    label: 'Roof',
    category: 'structures',
    defaultSize: { widthFt: 20, depthFt: 14, heightFt: 9 },
    minSize: { widthFt: 4, depthFt: 4, heightFt: 3 },
    maxSize: { widthFt: 80, depthFt: 40, heightFt: 20 },
    resizable: true,
    rotatable: true,
    color: '#7a6b5a',
    editableProps: [
      {
        key: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'flat', label: 'Flat' },
          { value: 'shed', label: 'Shed' },
          { value: 'gabled', label: 'Gabled' },
          { value: 'hip', label: 'Hip' },
        ],
        defaultValue: 'flat',
      },
      {
        key: 'pitch',
        label: 'Pitch (in/ft)',
        type: 'number',
        min: 1,
        max: 12,
        step: 1,
        defaultValue: 4,
      },
      {
        key: 'overhang',
        label: 'Overhang (in)',
        type: 'number',
        min: 0,
        max: 24,
        step: 3,
        defaultValue: 12,
      },
      {
        key: 'thickness',
        label: 'Thickness (in)',
        type: 'number',
        min: 4,
        max: 12,
        step: 1,
        defaultValue: 6,
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#7a6b5a',
      },
    ],
  },
  {
    type: 'concrete_slab',
    label: 'Concrete Slab',
    category: 'structures',
    defaultSize: { widthFt: 10, depthFt: 8, heightFt: 0.33 },
    minSize: { widthFt: 2, depthFt: 2, heightFt: 0.25 },
    maxSize: { widthFt: 100, depthFt: 100, heightFt: 1 },
    resizable: true,
    rotatable: true,
    color: '#a0a0a0',
    editableProps: [
      {
        key: 'finish',
        label: 'Finish',
        type: 'select',
        options: [
          { value: 'smooth', label: 'Smooth' },
          { value: 'textured', label: 'Textured' },
          { value: 'stamped', label: 'Stamped' },
        ],
        defaultValue: 'smooth',
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#a0a0a0',
      },
    ],
  },
  {
    type: 'fence_section',
    label: 'Fence Section',
    category: 'structures',
    defaultSize: { widthFt: 6, depthFt: 0.5, heightFt: 6 },
    minSize: { widthFt: 3, depthFt: 0.5, heightFt: 3 },
    maxSize: { widthFt: 12, depthFt: 0.5, heightFt: 8 },
    resizable: true,
    rotatable: true,
    color: '#c8a882',
  },

  {
    type: 'fireplace',
    label: 'Fireplace',
    category: 'structures',
    defaultSize: { widthFt: 5, depthFt: 2, heightFt: 4 },
    minSize: { widthFt: 4, depthFt: 1, heightFt: 3 },
    maxSize: { widthFt: 12, depthFt: 3, heightFt: 10 },
    resizable: true,
    rotatable: true,
    color: '#8a8070',
    editableProps: [
      {
        key: 'openingWidth',
        label: 'Opening Width',
        type: 'select',
        options: [
          { value: '40', label: '40"' },
          { value: '48', label: '48"' },
          { value: '60', label: '60"' },
          { value: '72', label: '72"' },
        ],
        defaultValue: '48',
      },
      {
        key: 'openingHeight',
        label: 'Opening Height (in)',
        type: 'number',
        min: 8,
        max: 24,
        step: 1,
        defaultValue: 12,
      },
      {
        key: 'openingPosition',
        label: 'Opening Position',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'center',
      },
      {
        key: 'hasHearth',
        label: 'Hearth',
        type: 'boolean',
        defaultValue: true,
      },
      {
        key: 'hearthHeight',
        label: 'Hearth Height (in)',
        type: 'number',
        min: 0,
        max: 24,
        step: 1,
        defaultValue: 0,
      },
      {
        key: 'material',
        label: 'Material',
        type: 'select',
        options: [
          { value: 'stone', label: 'Stone' },
          { value: 'brick', label: 'Brick' },
          { value: 'stucco', label: 'Stucco' },
          { value: 'concrete', label: 'Concrete' },
        ],
        defaultValue: 'stone',
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#8a8070',
      },
    ],
  },

  // ── Cooking & Kitchen ──
  {
    type: 'kitchen_straight',
    label: 'Kitchen (Straight)',
    category: 'cooking',
    defaultSize: { widthFt: 8, depthFt: 3, heightFt: 3 },
    minSize: { widthFt: 2, depthFt: 1.5, heightFt: 1.5 },
    maxSize: { widthFt: 16, depthFt: 4, heightFt: 3.5 },
    resizable: true,
    rotatable: true,
    color: '#6b6b6b',
    editableProps: [
      {
        key: 'material',
        label: 'Material',
        type: 'select',
        options: [
          { value: 'stone', label: 'Stone' },
          { value: 'brick', label: 'Brick' },
          { value: 'stucco', label: 'Stucco' },
          { value: 'concrete', label: 'Concrete' },
        ],
        defaultValue: 'stone',
      },
      {
        key: 'color',
        label: 'Base Color',
        type: 'color',
        defaultValue: '#6b6b6b',
      },
      {
        key: 'countertopColor',
        label: 'Countertop Color',
        type: 'color',
        defaultValue: '#404040',
      },
      {
        key: 'hasEggStand',
        label: 'Green Egg Stand',
        type: 'boolean',
        defaultValue: false,
      },
      {
        key: 'eggMounting',
        label: 'Egg Mounting',
        type: 'select',
        options: [
          { value: 'inset', label: 'Inset' },
          { value: 'on_top', label: 'On Top' },
        ],
        defaultValue: 'inset',
      },
      {
        key: 'eggStandSide',
        label: 'Stand Side',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'right',
      },
      {
        key: 'eggStandWidth',
        label: 'Stand Width (in)',
        type: 'number',
        min: 24,
        max: 48,
        step: 1,
        defaultValue: 30,
      },
      {
        key: 'eggStandHeight',
        label: 'Stand Height (in)',
        type: 'number',
        min: 12,
        max: 24,
        step: 1,
        defaultValue: 12,
      },
    ],
  },
  {
    type: 'kitchen_l_shaped',
    label: 'Kitchen (L-Shape)',
    category: 'cooking',
    defaultSize: { widthFt: 8, depthFt: 8, heightFt: 3 },
    minSize: { widthFt: 5, depthFt: 5, heightFt: 3 },
    maxSize: { widthFt: 14, depthFt: 14, heightFt: 3.5 },
    resizable: true,
    rotatable: true,
    color: '#6b6b6b',
    editableProps: [
      {
        key: 'legWidth',
        label: 'Leg Width (ft)',
        type: 'number',
        min: 2,
        max: 4,
        step: 0.5,
        defaultValue: 3,
      },
      {
        key: 'material',
        label: 'Material',
        type: 'select',
        options: [
          { value: 'stone', label: 'Stone' },
          { value: 'brick', label: 'Brick' },
          { value: 'stucco', label: 'Stucco' },
          { value: 'concrete', label: 'Concrete' },
        ],
        defaultValue: 'stone',
      },
      {
        key: 'color',
        label: 'Base Color',
        type: 'color',
        defaultValue: '#6b6b6b',
      },
      {
        key: 'countertopColor',
        label: 'Countertop Color',
        type: 'color',
        defaultValue: '#404040',
      },
      {
        key: 'hasEggStand',
        label: 'Green Egg Stand',
        type: 'boolean',
        defaultValue: false,
      },
      {
        key: 'eggMounting',
        label: 'Egg Mounting',
        type: 'select',
        options: [
          { value: 'inset', label: 'Inset' },
          { value: 'on_top', label: 'On Top' },
        ],
        defaultValue: 'inset',
      },
      {
        key: 'eggStandSide',
        label: 'Stand Side',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'right',
      },
      {
        key: 'eggStandWidth',
        label: 'Stand Width (in)',
        type: 'number',
        min: 24,
        max: 48,
        step: 1,
        defaultValue: 30,
      },
      {
        key: 'eggStandHeight',
        label: 'Stand Height (in)',
        type: 'number',
        min: 12,
        max: 24,
        step: 1,
        defaultValue: 12,
      },
    ],
  },
  {
    type: 'grill_builtin_small',
    label: 'Grill (Small)',
    category: 'cooking',
    defaultSize: { widthFt: 3, depthFt: 2, heightFt: 3 },
    minSize: { widthFt: 3, depthFt: 2, heightFt: 3 },
    maxSize: { widthFt: 3, depthFt: 2, heightFt: 3 },
    resizable: false,
    rotatable: true,
    color: '#b0b0b0',
  },
  {
    type: 'grill_builtin_large',
    label: 'Grill (Large)',
    category: 'cooking',
    defaultSize: { widthFt: 5, depthFt: 3, heightFt: 3.5 },
    minSize: { widthFt: 5, depthFt: 3, heightFt: 3.5 },
    maxSize: { widthFt: 5, depthFt: 3, heightFt: 3.5 },
    resizable: false,
    rotatable: true,
    color: '#b0b0b0',
  },
  {
    type: 'smoker',
    label: 'Smoker / Green Egg',
    category: 'cooking',
    defaultSize: { widthFt: 2.5, depthFt: 2.5, heightFt: 3 },
    minSize: { widthFt: 1.5, depthFt: 1.5, heightFt: 2.5 },
    maxSize: { widthFt: 4, depthFt: 4, heightFt: 4 },
    resizable: true,
    rotatable: true,
    color: '#2a5e2a',
    editableProps: [
      {
        key: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'egg', label: 'Kamado / Egg' },
          { value: 'barrel', label: 'Barrel Smoker' },
        ],
        defaultValue: 'egg',
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#2a5e2a',
      },
    ],
  },

  // ── Seating & Furniture ──
  {
    type: 'dining_table',
    label: 'Dining Table',
    category: 'seating',
    defaultSize: { widthFt: 6, depthFt: 3, heightFt: 2.5 },
    minSize: { widthFt: 2, depthFt: 2, heightFt: 2.5 },
    maxSize: { widthFt: 12, depthFt: 12, heightFt: 2.5 },
    resizable: false,
    rotatable: true,
    color: '#a0724a',
    editableProps: [
      {
        key: 'shape',
        label: 'Shape',
        type: 'select',
        options: [
          { value: 'round', label: 'Round' },
          { value: 'square', label: 'Square' },
          { value: 'rectangle', label: 'Rectangle' },
        ],
        defaultValue: 'rectangle',
      },
      {
        key: 'diameter',
        label: 'Diameter (in)',
        type: 'number',
        min: 36,
        max: 84,
        step: 6,
        defaultValue: 48,
      },
      {
        key: 'tableLength',
        label: 'Length (in)',
        type: 'number',
        min: 36,
        max: 120,
        step: 6,
        defaultValue: 72,
      },
      {
        key: 'tableWidth',
        label: 'Width (in)',
        type: 'number',
        min: 24,
        max: 60,
        step: 6,
        defaultValue: 36,
      },
      {
        key: 'sideLength',
        label: 'Side Length (in)',
        type: 'number',
        min: 24,
        max: 72,
        step: 6,
        defaultValue: 42,
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#a0724a',
      },
    ],
  },
  {
    type: 'chair',
    label: 'Chair',
    category: 'seating',
    defaultSize: { widthFt: 2, depthFt: 2, heightFt: 3 },
    minSize: { widthFt: 1.5, depthFt: 1.5, heightFt: 3 },
    maxSize: { widthFt: 3, depthFt: 3, heightFt: 3 },
    resizable: true,
    rotatable: true,
    color: '#6b8e6b',
    editableProps: [
      {
        key: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'standard', label: 'Standard' },
          { value: 'adirondack', label: 'Adirondack' },
          { value: 'rocking', label: 'Rocking' },
        ],
        defaultValue: 'standard',
      },
      {
        key: 'hasArmrests',
        label: 'Armrests',
        type: 'boolean',
        defaultValue: false,
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#6b8e6b',
      },
    ],
  },
  {
    type: 'club_chair',
    label: 'Club Chair',
    category: 'seating',
    defaultSize: { widthFt: 3, depthFt: 3, heightFt: 2.5 },
    minSize: { widthFt: 2.5, depthFt: 2.5, heightFt: 2 },
    maxSize: { widthFt: 4, depthFt: 4, heightFt: 3.5 },
    resizable: true,
    rotatable: true,
    color: '#7a8a7a',
    editableProps: [
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#7a8a7a',
      },
    ],
  },
  {
    type: 'lounge_set',
    label: 'Lounge Set',
    category: 'seating',
    defaultSize: { widthFt: 8, depthFt: 8, heightFt: 3 },
    minSize: { widthFt: 5, depthFt: 5, heightFt: 3 },
    maxSize: { widthFt: 14, depthFt: 14, heightFt: 3 },
    resizable: true,
    rotatable: true,
    color: '#7a8a7a',
  },
  {
    type: 'couch',
    label: 'Couch',
    category: 'seating',
    defaultSize: { widthFt: 7, depthFt: 3, heightFt: 2.5 },
    minSize: { widthFt: 4, depthFt: 2.5, heightFt: 2 },
    maxSize: { widthFt: 10, depthFt: 4, heightFt: 3.5 },
    resizable: true,
    rotatable: true,
    color: '#7a8a7a',
    editableProps: [
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#7a8a7a',
      },
    ],
  },
  {
    type: 'sectional',
    label: 'Sectional',
    category: 'seating',
    defaultSize: { widthFt: 10, depthFt: 8, heightFt: 2.5 },
    minSize: { widthFt: 6, depthFt: 6, heightFt: 2 },
    maxSize: { widthFt: 14, depthFt: 14, heightFt: 3.5 },
    resizable: true,
    rotatable: true,
    color: '#7a8a7a',
    editableProps: [
      {
        key: 'lSide',
        label: 'Chaise Side',
        type: 'select',
        options: [
          { value: 'left', label: 'Left' },
          { value: 'right', label: 'Right' },
        ],
        defaultValue: 'left',
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#7a8a7a',
      },
    ],
  },
  {
    type: 'end_table',
    label: 'End Table',
    category: 'seating',
    defaultSize: { widthFt: 2, depthFt: 2, heightFt: 1.75 },
    minSize: { widthFt: 1, depthFt: 1, heightFt: 1.5 },
    maxSize: { widthFt: 3, depthFt: 3, heightFt: 2 },
    resizable: false,
    rotatable: true,
    color: '#a0724a',
    editableProps: [
      {
        key: 'shape',
        label: 'Shape',
        type: 'select',
        options: [
          { value: 'round', label: 'Round' },
          { value: 'square', label: 'Square' },
          { value: 'rectangle', label: 'Rectangle' },
        ],
        defaultValue: 'round',
      },
      {
        key: 'diameter',
        label: 'Diameter (in)',
        type: 'number',
        min: 12,
        max: 30,
        step: 2,
        defaultValue: 20,
      },
      {
        key: 'tableLength',
        label: 'Length (in)',
        type: 'number',
        min: 18,
        max: 36,
        step: 2,
        defaultValue: 24,
      },
      {
        key: 'tableWidth',
        label: 'Width (in)',
        type: 'number',
        min: 12,
        max: 24,
        step: 2,
        defaultValue: 18,
      },
      {
        key: 'sideLength',
        label: 'Side Length (in)',
        type: 'number',
        min: 12,
        max: 30,
        step: 2,
        defaultValue: 20,
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#a0724a',
      },
    ],
  },
  {
    type: 'coffee_table',
    label: 'Coffee Table',
    category: 'seating',
    defaultSize: { widthFt: 4, depthFt: 2, heightFt: 1.33 },
    minSize: { widthFt: 2, depthFt: 1.5, heightFt: 1 },
    maxSize: { widthFt: 6, depthFt: 4, heightFt: 1.75 },
    resizable: false,
    rotatable: true,
    color: '#a0724a',
    editableProps: [
      {
        key: 'shape',
        label: 'Shape',
        type: 'select',
        options: [
          { value: 'round', label: 'Round' },
          { value: 'square', label: 'Square' },
          { value: 'rectangle', label: 'Rectangle' },
        ],
        defaultValue: 'rectangle',
      },
      {
        key: 'diameter',
        label: 'Diameter (in)',
        type: 'number',
        min: 24,
        max: 48,
        step: 6,
        defaultValue: 36,
      },
      {
        key: 'tableLength',
        label: 'Length (in)',
        type: 'number',
        min: 30,
        max: 72,
        step: 6,
        defaultValue: 48,
      },
      {
        key: 'tableWidth',
        label: 'Width (in)',
        type: 'number',
        min: 18,
        max: 36,
        step: 6,
        defaultValue: 24,
      },
      {
        key: 'sideLength',
        label: 'Side Length (in)',
        type: 'number',
        min: 24,
        max: 48,
        step: 6,
        defaultValue: 36,
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#a0724a',
      },
    ],
  },

  // ── Landscaping ──
  {
    type: 'fire_pit',
    label: 'Fire Pit',
    category: 'landscaping',
    defaultSize: { widthFt: 4, depthFt: 4, heightFt: 1.5 },
    minSize: { widthFt: 2, depthFt: 2, heightFt: 0.5 },
    maxSize: { widthFt: 8, depthFt: 8, heightFt: 3 },
    resizable: false,
    rotatable: true,
    color: '#d44a00',
    editableProps: [
      {
        key: 'shape',
        label: 'Shape',
        type: 'select',
        options: [
          { value: 'round', label: 'Round' },
          { value: 'square', label: 'Square' },
          { value: 'rectangle', label: 'Rectangle' },
        ],
        defaultValue: 'round',
      },
      {
        key: 'diameter',
        label: 'Diameter (in)',
        type: 'number',
        min: 24,
        max: 96,
        step: 1,
        defaultValue: 48,
      },
      {
        key: 'sideLength',
        label: 'Side Length (in)',
        type: 'number',
        min: 24,
        max: 96,
        step: 1,
        defaultValue: 48,
      },
      {
        key: 'pitLength',
        label: 'Length (in)',
        type: 'number',
        min: 36,
        max: 96,
        step: 1,
        defaultValue: 60,
      },
      {
        key: 'pitWidth',
        label: 'Width (in)',
        type: 'number',
        min: 24,
        max: 72,
        step: 1,
        defaultValue: 36,
      },
      {
        key: 'pitHeight',
        label: 'Height (in)',
        type: 'number',
        min: 6,
        max: 36,
        step: 1,
        defaultValue: 18,
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#d44a00',
      },
    ],
  },
  {
    type: 'planter_box',
    label: 'Planter Box',
    category: 'landscaping',
    defaultSize: { widthFt: 4, depthFt: 2, heightFt: 2 },
    minSize: { widthFt: 2, depthFt: 1, heightFt: 1 },
    maxSize: { widthFt: 10, depthFt: 4, heightFt: 4 },
    resizable: true,
    rotatable: true,
    color: '#6b4226',
  },
  {
    type: 'tree_small',
    label: 'Tree',
    category: 'landscaping',
    defaultSize: { widthFt: 3, depthFt: 3, heightFt: 8 },
    minSize: { widthFt: 2, depthFt: 2, heightFt: 3 },
    maxSize: { widthFt: 15, depthFt: 15, heightFt: 30 },
    resizable: false,
    rotatable: false,
    color: '#2d5a27',
    editableProps: [
      {
        key: 'treeType',
        label: 'Type',
        type: 'select',
        options: [
          { value: 'deciduous', label: 'Deciduous' },
          { value: 'evergreen', label: 'Evergreen' },
          { value: 'palm', label: 'Palm' },
          { value: 'ornamental', label: 'Ornamental' },
        ],
        defaultValue: 'deciduous',
      },
      {
        key: 'treeSize',
        label: 'Size',
        type: 'select',
        options: [
          { value: 'small', label: 'Small' },
          { value: 'medium', label: 'Medium' },
          { value: 'large', label: 'Large' },
        ],
        defaultValue: 'small',
      },
      {
        key: 'color',
        label: 'Foliage Color',
        type: 'color',
        defaultValue: '#2d5a27',
      },
    ],
  },
  {
    type: 'shrub',
    label: 'Shrub',
    category: 'landscaping',
    defaultSize: { widthFt: 3, depthFt: 3, heightFt: 3 },
    minSize: { widthFt: 1, depthFt: 1, heightFt: 1 },
    maxSize: { widthFt: 8, depthFt: 8, heightFt: 6 },
    resizable: true,
    rotatable: false,
    color: '#3a7a2a',
    editableProps: [
      {
        key: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'round', label: 'Round' },
          { value: 'boxwood', label: 'Boxwood' },
          { value: 'natural', label: 'Natural' },
        ],
        defaultValue: 'round',
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#3a7a2a',
      },
    ],
  },
  {
    type: 'flower_bed',
    label: 'Flower Bed',
    category: 'landscaping',
    defaultSize: { widthFt: 4, depthFt: 2, heightFt: 1.5 },
    minSize: { widthFt: 1, depthFt: 1, heightFt: 0.5 },
    maxSize: { widthFt: 12, depthFt: 8, heightFt: 3 },
    resizable: true,
    rotatable: true,
    color: '#d94080',
    editableProps: [
      {
        key: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { value: 'mixed', label: 'Mixed' },
          { value: 'roses', label: 'Roses' },
          { value: 'grasses', label: 'Grasses' },
          { value: 'tropical', label: 'Tropical' },
        ],
        defaultValue: 'mixed',
      },
      {
        key: 'color',
        label: 'Flower Color',
        type: 'color',
        defaultValue: '#d94080',
      },
      {
        key: 'bedColor',
        label: 'Bed/Mulch Color',
        type: 'color',
        defaultValue: '#5a3a1a',
      },
    ],
  },
  {
    type: 'retaining_wall',
    label: 'Retaining Wall',
    category: 'landscaping',
    defaultSize: { widthFt: 10, depthFt: 1 / 3, heightFt: 2 },
    minSize: { widthFt: 1, depthFt: 1 / 12, heightFt: 0.5 },
    maxSize: { widthFt: 60, depthFt: 2, heightFt: 6 },
    resizable: false,
    rotatable: true,
    color: '#8a7d6b',
    editableProps: [
      {
        key: 'wallLength',
        label: 'Length (in)',
        type: 'number',
        min: 24,
        max: 720,
        step: 6,
        defaultValue: 120,
      },
      {
        key: 'wallHeight',
        label: 'Height (in)',
        type: 'number',
        min: 6,
        max: 72,
        step: 3,
        defaultValue: 24,
      },
      {
        key: 'wallThickness',
        label: 'Thickness (in)',
        type: 'number',
        min: 4,
        max: 24,
        step: 2,
        defaultValue: 4,
      },
      {
        key: 'material',
        label: 'Material',
        type: 'select',
        options: [
          { value: 'block', label: 'Block' },
          { value: 'stone', label: 'Natural Stone' },
          { value: 'timber', label: 'Timber' },
          { value: 'concrete', label: 'Concrete' },
          { value: 'brick', label: 'Brick' },
        ],
        defaultValue: 'block',
      },
      {
        key: 'capStyle',
        label: 'Cap',
        type: 'select',
        options: [
          { value: 'none', label: 'None' },
          { value: 'flat', label: 'Flat Cap' },
          { value: 'bullnose', label: 'Bullnose' },
        ],
        defaultValue: 'flat',
      },
      {
        key: 'color',
        label: 'Color',
        type: 'color',
        defaultValue: '#8a7d6b',
      },
    ],
  },
]
